spring:
  data:
    mongodb:
      uri: mongodb+srv://udaykumarkella67:frod02zmjQhhhqbR@cluster0.wwn8ujw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

server:
  port: 8081
#  servlet:
#    context-path: /jApp